DELETE http://localhost:3003/api/blogs/634d4682a491dd4afc475c15
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJpZCI6IjYzNGQ0MjZjODU3YjNlMzdiYzcwZmEzNSIsImlhdCI6MTY2NjAwNzY5MSwiZXhwIjoxNjY2MDExMjkxfQ.HjkZJwf1sPBI-s-hY4r3Dlh3AdVyXD-CEgg5cEZqpqI