POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlZXZpQHVybC5maSIsImlkIjoxLCJpYXQiOjE2NzAyNTIzMzN9.1JzdKQ8UMLIXBSS1eGGwFlmsAvWdrGvjlcOdaIKXLq4

{
  "author": "leevi",
  "url": "toinen",
  "title": "blogi",
  "likes": 100,
  "year": 2022
}